### ISSUE TITLE
Error when running 'roslaunch ocrtoc_task trigger.launch task_index:=0-0'

### ISSUE THREAD

**Issue by Skylark0924** [OCRTOC/OCRTOC_software_package#11]
When running `roslaunch ocrtoc_task trigger.launch task_index:=0-0`, I got this error:

```
process[trigger-1]: started with pid [1072]
Traceback (most recent call last):
  File "/root/ocrtoc_ws/src/ocrtoc_task/scripts/trigger.py", line 13, in <module>
    from grasp_detection import Grasp_Detector
  File "/root/ocrtoc_ws/src/ocrtoc_task/scripts/grasp_detection.py", line 19, in <module>
    from ocrtoc_common.transform_interface import TransformInterface
ImportError: No module named ocrtoc_common.transform_interface
[trigger-1] process has died [pid 1072, exit code 1, cmd /root/ocrtoc_ws/src/ocrtoc_task/scripts/trigger.py __name:=trigger __log:=/root/.ros/log/49e883fe-4306-11ec-8f7a-3c7c3f2de8b9/trigger-1.log].
log file: /root/.ros/log/49e883fe-4306-11ec-8f7a-3c7c3f2de8b9/trigger-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

I `rosrun` that py script only, and got this:
```
root@computer1:~/ocrtoc_ws/src/ocrtoc_task/scripts# rosrun ocrtoc_task grasp_detection.py 
Traceback (most recent call last):
  File "/root/ocrtoc_ws/src/ocrtoc_task/scripts/grasp_detection.py", line 19, in <module>
    from ocrtoc_common.transform_interface import TransformInterface
ImportError: No module named ocrtoc_common.transform_interface
```

**Comment by GouMinghao** [comment]
Could you please tell what is the problem?

**Comment by Skylark0924** [comment]
I cloned it in a Windows and transfer it to my Ubuntu server, so this error is caused by the wrong code style in these two systems. After I downloaded it directly on ubuntu, the problem was solved.

**Comment by emigmo** [comment]
The same problem still exists in version 2.1. 
This problem does not exist in the previous version
